import os
from typing import Dict, List, Tuple
from generator.template.utility import writer

template = """
//*************************************************************************************
//   !!! Generated by the fmp-cli.  DO NOT EDIT!
//*************************************************************************************

using System;
using XTC.FMP.LIB.MVCS;

public class ConsoleLogger : Logger
{

    protected override void trace(string _category, string _message)
    {
        Console.WriteLine($"TRACE [{_category}] - {_message}");
    }

    protected override void debug(string _category, string _message)
    {
        Console.WriteLine($"DEBUG [{_category}] - {_message}");
    }

    protected override void info(string _category, string _message)
    {
        Console.WriteLine($"INFO [{_category}] - {_message}");
    }

    protected override void warning(string _category, string _message)
    {
        Console.WriteLine($"WARN [{_category}] - {_message}");
    }

    protected override void error(string _category, string _message)
    {
        Console.WriteLine($"ERROR [{_category}] - {_message}");
    }

    protected override void exception(Exception _exception)
    {
        Console.WriteLine($"EXCEPTION  - {_exception.Message}");
        Console.WriteLine($"EXCEPTION  - {_exception.StackTrace}");
    }
}

"""


def generate(
    _orgname: str,
    _modulename: str,
    _outputdir: str,
):
    filepath = os.path.join(_outputdir, "ConsoleLogger.cs")
    writer.write(filepath, template, True)
