import os
from typing import Dict, List, Tuple
from generator.template.utility import writer

template = """
//*************************************************************************************
//   !!! Generated by the fmp-cli.  DO NOT EDIT!
//*************************************************************************************

using System;
using System.Net.Http;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Components.WebAssembly.Hosting;
using Microsoft.Extensions.DependencyInjection;
using Grpc.Net.Client;
using Grpc.Net.Client.Web;
using AntDesign.ProLayout;
using XTC.FMP.LIB.MVCS;
using {{org}}.FMP.MOD.{{module}}.LIB.MVCS;
using {{org}}.FMP.MOD.{{module}}.App.Web;

public partial class Program
{
    public static async Task Main(string[] args)
    {
        var channel = GrpcChannel.ForAddress("https://localhost:19000/", new GrpcChannelOptions
        {
            HttpHandler = new GrpcWebHandler(new HttpClientHandler())
        });

        Logger logger = new ConsoleLogger();
        Framework framework = new Framework();
        framework.setConfig(new Config());
        framework.setLogger(logger);
        framework.Initialize();

        framework.Setup();
        var builder = WebAssemblyHostBuilder.CreateDefault(args);
        builder.RootComponents.Add<App>("#app");

        builder.Services.AddScoped(sp => framework);
        builder.Services.AddScoped(sp => logger);
        builder.Services.AddScoped(sp => new HttpClient { BaseAddress = new Uri(builder.HostEnvironment.BaseAddress) });
        builder.Services.AddAntDesign();
        builder.Services.Configure<ProSettings>(builder.Configuration.GetSection("ProSettings"));

        var entry = new Entry();
        var options = new Options();
        options.setChannel(channel);
        framework.setUserData("{{org}}.FMP.MOD.{{module}}.LIB.MVCS.Entry", entry);
        entry.Inject(framework, options);
        entry.DynamicRegister(logger);
        await builder.Build().RunAsync();

        framework.Dismantle();
        entry.StaticCancel(logger);
        framework.Release();
    }
}
"""

def generate(
    _orgname: str,
    _modulename: str,
    _outputdir: str,
    _enums: List[str],
    _services: Dict[str, Dict[str, Tuple]],
    _messages: Dict[str, List[Tuple]],
):
    contents = (
        template.replace("{{org}}", _orgname)
        .replace("{{module}}", _modulename)
    )
    filepath = os.path.join(_outputdir, "Program.cs")
    writer.write(filepath, contents, True)
