import os
from typing import Dict, List, Tuple
from generator.template.utility import writer

template_mongodb = """
//*************************************************************************************
//   !!! Generated by the fmp-cli {{version}}.  DO NOT EDIT!
//*************************************************************************************

namespace {{org}}.FMP.MOD.{{module}}.App.Service
{
    /// <summary>
    /// 数据库设置
    /// </summary>
    public class DatabaseSettings
    {
        /// <summary>
        /// 驱动
        /// </summary>
        public string Driver { get; set; } = "MongoDB";

        /// <summary>
        /// 连接字符
        /// </summary>
        public string ConnectionString { get; set; } = null!;

        /// <summary>
        /// 数据库名
        /// </summary>
        public string DatabaseName { get; set; } = null!;
    }
}
"""


def generate(_options, _outputdir: str):
    org_name = _options["org_name"]
    module_name = _options["module_name"]
    database_driver = _options["database_driver"]

    if "mongodb" == database_driver:
        contents = template_mongodb.replace("{{org}}", org_name).replace(
            "{{module}}", module_name
        )
        contents = contents.replace("{{version}}", _options["version"])
        filepath = os.path.join(_outputdir, "DatabaseSettings.cs")
        writer.write(filepath, contents, True)
