import os
from typing import Dict, List, Tuple
from generator.template.utility import writer

template_mongodb = """
//*************************************************************************************
//   !!! Generated by the fmp-cli.  DO NOT EDIT!
//*************************************************************************************

namespace {{org}}.FMP.MOD.{{module}}.App.Service
{
    /// <summary>
    /// 数据库设置
    /// </summary>
    public class DatabaseSettings
    {
        /// <summary>
        /// 驱动
        /// </summary>
        public string Driver { get; set; } = "MongoDB";

        /// <summary>
        /// 连接字符
        /// </summary>
        public string ConnectionString { get; set; } = null!;

        /// <summary>
        /// 数据库名
        /// </summary>
        public string DatabaseName { get; set; } = null!;
    }
}
"""

def generate(
    _orgname: str,
    _modulename: str,
    _outputdir: str,
    _databasedriver: str,
):
    if "mongodb" == _databasedriver:
        contents = template_mongodb.replace("{{org}}", _orgname).replace("{{module}}", _modulename)
        filepath = os.path.join(_outputdir, "DatabaseSettings.cs")
        writer.write(filepath, contents, True)
