import os
from typing import Dict, List, Tuple
from generator.template.utility import writer

template_mongodb = """
//*************************************************************************************
//   !!! Generated by the fmp-cli {{version}}.  DO NOT EDIT!
//*************************************************************************************

using MongoDB.Bson.Serialization.Attributes;
using MongoDB.Bson.Serialization.IdGenerators;

namespace {{org}}.FMP.MOD.{{module}}.App.Service
{
    /// <summary>
    /// 数据实体
    /// </summary>
    /// <example>
    /// public class YourEntity: Entity
    /// {
    /// }
    /// </example>
    public class Entity
    {
        /// <summary>
        /// MongoDB的ObjectId
        /// </summary>
        [BsonId]
        [BsonRepresentation(MongoDB.Bson.BsonType.ObjectId)]
        private string? _id{ get; set; }

        /// <summary>
        /// 实体的唯一识别ID
        /// </summary>
        public Guid? Uuid { get; set; }
    }
}
"""


def generate(_options, _outputdir: str):
    org_name = _options["org_name"]
    module_name = _options["module_name"]
    database_driver = _options["database_driver"]

    if "mongodb" == database_driver:
        contents = template_mongodb.replace("{{org}}", org_name).replace(
            "{{module}}", module_name
        )
        contents = contents.replace("{{version}}", _options["version"])
        filepath = os.path.join(_outputdir, "Entity.cs")
        writer.write(filepath, contents, True)
