import os
from generator.template.utility import writer

template = """
//*************************************************************************************
//   !!! Generated by the fmp-cli {{version}}.  DO NOT EDIT!
//*************************************************************************************

namespace {{org}}.FMP.MOD.{{module}}.LIB.Bridge
{
    /// <summary>
    /// 数据传输对象
    /// </summary>
    public interface IDTO
    {
    }
}
"""


def generate(_options, _outputdir: str):
    org_name = _options["org_name"]
    module_name = _options["module_name"]
    # 生成项目文件
    contents = template.replace("{{org}}", org_name).replace("{{module}}", module_name)
    contents = contents.replace("{{version}}", _options["version"])
    filepath = os.path.join(_outputdir, "IDTO.cs")
    writer.write(filepath, contents, True)
