import os
from generator.template.utility import writer

template = """
//*************************************************************************************
//   !!! Generated by the fmp-cli.  DO NOT EDIT!
//*************************************************************************************

namespace {{org}}.FMP.MOD.{{module}}.LIB.Bridge
{
    /// <summary>
    /// 数据传输对象
    /// </summary>
    public interface IDTO
    {
    }
}
"""

def generate(_orgname: str, _modulename: str, _outputdir: str):
    # 生成项目文件
    contents = template.replace("{{org}}", _orgname).replace("{{module}}", _modulename)
    filepath = os.path.join(_outputdir, 'IDTO.cs')
    writer.write(filepath, contents, True)
