# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from mygrpc import module_pb2 as module__pb2
from mygrpc import shared_pb2 as shared__pb2


class ModuleStub(object):
    """插件
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Create = channel.unary_unary(
                '/xtc.fmp.repository.Module/Create',
                request_serializer=module__pb2.ModuleCreateRequest.SerializeToString,
                response_deserializer=shared__pb2.UuidResponse.FromString,
                )
        self.Update = channel.unary_unary(
                '/xtc.fmp.repository.Module/Update',
                request_serializer=module__pb2.ModuleUpdateRequest.SerializeToString,
                response_deserializer=shared__pb2.UuidResponse.FromString,
                )
        self.Retrieve = channel.unary_unary(
                '/xtc.fmp.repository.Module/Retrieve',
                request_serializer=shared__pb2.UuidRequest.SerializeToString,
                response_deserializer=module__pb2.ModuleRetrieveResponse.FromString,
                )
        self.Delete = channel.unary_unary(
                '/xtc.fmp.repository.Module/Delete',
                request_serializer=shared__pb2.UuidRequest.SerializeToString,
                response_deserializer=shared__pb2.UuidResponse.FromString,
                )
        self.List = channel.unary_unary(
                '/xtc.fmp.repository.Module/List',
                request_serializer=module__pb2.ModuleListRequest.SerializeToString,
                response_deserializer=module__pb2.ModuleListResponse.FromString,
                )
        self.Search = channel.unary_unary(
                '/xtc.fmp.repository.Module/Search',
                request_serializer=module__pb2.ModuleSearchRequest.SerializeToString,
                response_deserializer=module__pb2.ModuleListResponse.FromString,
                )
        self.PrepareUpload = channel.unary_unary(
                '/xtc.fmp.repository.Module/PrepareUpload',
                request_serializer=shared__pb2.UuidRequest.SerializeToString,
                response_deserializer=shared__pb2.PrepareUploadResponse.FromString,
                )
        self.FlushUpload = channel.unary_unary(
                '/xtc.fmp.repository.Module/FlushUpload',
                request_serializer=shared__pb2.UuidRequest.SerializeToString,
                response_deserializer=shared__pb2.FlushUploadResponse.FromString,
                )
        self.AddFlag = channel.unary_unary(
                '/xtc.fmp.repository.Module/AddFlag',
                request_serializer=shared__pb2.FlagOperationRequest.SerializeToString,
                response_deserializer=shared__pb2.FlagOperationResponse.FromString,
                )
        self.RemoveFlag = channel.unary_unary(
                '/xtc.fmp.repository.Module/RemoveFlag',
                request_serializer=shared__pb2.FlagOperationRequest.SerializeToString,
                response_deserializer=shared__pb2.FlagOperationResponse.FromString,
                )


class ModuleServicer(object):
    """插件
    """

    def Create(self, request, context):
        """创建
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Update(self, request, context):
        """更新
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Retrieve(self, request, context):
        """读取
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """删除
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def List(self, request, context):
        """列举
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Search(self, request, context):
        """搜索
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PrepareUpload(self, request, context):
        """准备上传
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FlushUpload(self, request, context):
        """完成上传
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddFlag(self, request, context):
        """添加标志
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveFlag(self, request, context):
        """移除标志
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ModuleServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=module__pb2.ModuleCreateRequest.FromString,
                    response_serializer=shared__pb2.UuidResponse.SerializeToString,
            ),
            'Update': grpc.unary_unary_rpc_method_handler(
                    servicer.Update,
                    request_deserializer=module__pb2.ModuleUpdateRequest.FromString,
                    response_serializer=shared__pb2.UuidResponse.SerializeToString,
            ),
            'Retrieve': grpc.unary_unary_rpc_method_handler(
                    servicer.Retrieve,
                    request_deserializer=shared__pb2.UuidRequest.FromString,
                    response_serializer=module__pb2.ModuleRetrieveResponse.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=shared__pb2.UuidRequest.FromString,
                    response_serializer=shared__pb2.UuidResponse.SerializeToString,
            ),
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=module__pb2.ModuleListRequest.FromString,
                    response_serializer=module__pb2.ModuleListResponse.SerializeToString,
            ),
            'Search': grpc.unary_unary_rpc_method_handler(
                    servicer.Search,
                    request_deserializer=module__pb2.ModuleSearchRequest.FromString,
                    response_serializer=module__pb2.ModuleListResponse.SerializeToString,
            ),
            'PrepareUpload': grpc.unary_unary_rpc_method_handler(
                    servicer.PrepareUpload,
                    request_deserializer=shared__pb2.UuidRequest.FromString,
                    response_serializer=shared__pb2.PrepareUploadResponse.SerializeToString,
            ),
            'FlushUpload': grpc.unary_unary_rpc_method_handler(
                    servicer.FlushUpload,
                    request_deserializer=shared__pb2.UuidRequest.FromString,
                    response_serializer=shared__pb2.FlushUploadResponse.SerializeToString,
            ),
            'AddFlag': grpc.unary_unary_rpc_method_handler(
                    servicer.AddFlag,
                    request_deserializer=shared__pb2.FlagOperationRequest.FromString,
                    response_serializer=shared__pb2.FlagOperationResponse.SerializeToString,
            ),
            'RemoveFlag': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveFlag,
                    request_deserializer=shared__pb2.FlagOperationRequest.FromString,
                    response_serializer=shared__pb2.FlagOperationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'xtc.fmp.repository.Module', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Module(object):
    """插件
    """

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/xtc.fmp.repository.Module/Create',
            module__pb2.ModuleCreateRequest.SerializeToString,
            shared__pb2.UuidResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/xtc.fmp.repository.Module/Update',
            module__pb2.ModuleUpdateRequest.SerializeToString,
            shared__pb2.UuidResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Retrieve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/xtc.fmp.repository.Module/Retrieve',
            shared__pb2.UuidRequest.SerializeToString,
            module__pb2.ModuleRetrieveResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/xtc.fmp.repository.Module/Delete',
            shared__pb2.UuidRequest.SerializeToString,
            shared__pb2.UuidResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/xtc.fmp.repository.Module/List',
            module__pb2.ModuleListRequest.SerializeToString,
            module__pb2.ModuleListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Search(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/xtc.fmp.repository.Module/Search',
            module__pb2.ModuleSearchRequest.SerializeToString,
            module__pb2.ModuleListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PrepareUpload(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/xtc.fmp.repository.Module/PrepareUpload',
            shared__pb2.UuidRequest.SerializeToString,
            shared__pb2.PrepareUploadResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def FlushUpload(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/xtc.fmp.repository.Module/FlushUpload',
            shared__pb2.UuidRequest.SerializeToString,
            shared__pb2.FlushUploadResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AddFlag(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/xtc.fmp.repository.Module/AddFlag',
            shared__pb2.FlagOperationRequest.SerializeToString,
            shared__pb2.FlagOperationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RemoveFlag(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/xtc.fmp.repository.Module/RemoveFlag',
            shared__pb2.FlagOperationRequest.SerializeToString,
            shared__pb2.FlagOperationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
