import os
from typing import Dict, List, Tuple
from generator.template.utility import writer

template = """
<!--
*************************************************************************************
   !!! Generated by the fmp-cli.  DO NOT EDIT!
*************************************************************************************
-->

@namespace {{org}}.FMP.MOD.{{module}}.App.Web
@inherits LayoutComponentBase

<AntDesign.ProLayout.BasicLayout 
    Logo="@("https://gw.alipayobjects.com/zos/rmsportal/KDpgvguMpGfqaHPjicRK.svg")"
    MenuData="_menuData">
    <RightContentRender>
        <Components.RightContent />
    </RightContentRender>
    <ChildContent>
        @Body
    </ChildContent>
    <FooterRender>
        <FooterView Copyright="2021 Ant Design Blazor" Links="Links"></FooterView>
    </FooterRender>
</AntDesign.ProLayout.BasicLayout>
<SettingDrawer />

@code
{
    private readonly MenuDataItem[] _menuData =
    {
        new MenuDataItem
        {
            Path = "/",
            Name = "welcome",
            Key = "welcome",
            Icon = "smile",
        },
{{menuitem_blocks}}
    };

    public LinkItem[] Links { get; set; } =
    {
    };
}
"""

template_menuitem = """
        new MenuDataItem
        {
            Path = "/{{org_lower}}/{{module_lower}}/{{service_lower}}",
            Name = "{{service}}",
            Key = "{{service}}",
            Icon = "smile",
        },
"""


def generate(
    _orgname: str,
    _modulename: str,
    _outputdir: str,
    _enums: List[str],
    _services: Dict[str, Dict[str, Tuple]],
    _messages: Dict[str, List[Tuple]],
):
    sub_dir = os.path.join(_outputdir, "Layouts")
    os.makedirs(sub_dir, exist_ok=True)

    menuitem_blocks = ""
    for service in _services.keys():
        menuitem_blocks = menuitem_blocks + template_menuitem.replace(
            "{{org_lower}}", _orgname.lower()
        ).replace("{{module_lower}}", _modulename.lower()).replace(
            "{{service_lower}}", service.lower()
        ).replace(
            "{{service}}", service
        )
    contents = (
        template.replace("{{org}}", _orgname)
        .replace("{{module}}", _modulename)
        .replace("{{menuitem_blocks}}", menuitem_blocks)
    )
    filepath = os.path.join(sub_dir, "BasicLayout.razor")
    writer.write(filepath, contents, True)
