import os
import uuid
from generator.template.utility import writer

template = """
//*************************************************************************************
//   !!! Generated by the fmp-cli {{version}}.  DO NOT EDIT!
//*************************************************************************************

using UnityEditor;
using UnityEngine;
using System.IO;

public static class BuildTools
{
    //--------------------------------
    // Settings
    //--------------------------------

    static string outpath = System.IO.Path.Combine(Application.dataPath, "../../_dist_");

    [MenuItem("BuildTools/AssetBundle/WebGL")]
    public static void BuildAssetBundleForWebGL()
    {
        buildAssetBundle(BuildTarget.WebGL);
    }

    [MenuItem("BuildTools/AssetBundle/Windows")]
    public static void BuildAssetBundleForWindows()
    {
        buildAssetBundle(BuildTarget.StandaloneWindows);
    }

    [MenuItem("BuildTools/AssetBundle/Android")]
    public static void BuildAssetBundleForAndroid()
    {
        buildAssetBundle(BuildTarget.Android);
    }

    private static void buildAssetBundle(BuildTarget _target)
    {
        Directory.CreateDirectory(outpath);
        string path = System.IO.Path.Combine(outpath, convertToPlatform(_target));
        Directory.CreateDirectory(path);
        Debug.Log(string.Format("build assetbundle at {0}", path));
        BuildPipeline.BuildAssetBundles(path, BuildAssetBundleOptions.ForceRebuildAssetBundle, _target);

        //remove unused files
        File.Delete(Path.Combine(path, convertToPlatform(_target)));
        File.Delete(Path.Combine(path, convertToPlatform(_target)) + ".manifest");
        foreach (string file in Directory.GetFiles(path))
        {
            if (!file.EndsWith(".manifest"))
                continue;
            string target = Path.Combine(path, Path.GetFileName(file));
            File.Delete(target);
        }
    }

    private static string convertToPlatform(BuildTarget _target)
    {
        if (BuildTarget.StandaloneWindows == _target)
            return "windows";
        if (BuildTarget.WebGL == _target)
            return "webgl";
        if (BuildTarget.Android == _target)
            return "android";
        return "unknow";
    }


}
"""

def generate(_options, _outputdir: str):
    output_dir = os.path.join(_outputdir, "Assets")
    os.makedirs(output_dir, exist_ok=True)
    output_dir = os.path.join(output_dir, "Editor")
    os.makedirs(output_dir, exist_ok=True)
    output_dir = os.path.join(output_dir, "_Generated_")
    os.makedirs(output_dir, exist_ok=True)

    contents = template.replace("{{version}}", _options["version"])
    output_path = os.path.join(output_dir, "PackageTools.cs")
    writer.write(output_path, contents, True)
