import os
from typing import Dict, List, Tuple
from generator.template.utility import writer

template = """
//*************************************************************************************
//   !!! Generated by the fmp-cli {{version}}.  DO NOT EDIT!
//*************************************************************************************

public abstract class IntegrationTestBase
{
    /// <summary>
    /// 测试上下文
    /// </summary>
    protected TestFixture fixture_ { get; set; }

    public IntegrationTestBase(TestFixture _testFixture)
    {
        fixture_ = _testFixture;
    }

    [Fact]
    public abstract Task Test();
}
"""


def generate(_options, _outputdir: str):
    contents = template.replace("{{version}}", _options["version"])
    filepath = os.path.join(_outputdir, "IntegrationTestBase.cs")
    writer.write(filepath, contents, True)
