import os
from typing import Dict, List, Tuple
from generator.template.utility import writer

template = """
//*************************************************************************************
//   !!! Generated by the fmp-cli {{version}}.  DO NOT EDIT!
//*************************************************************************************

using XTC.FMP.LIB.MVCS;
using {{org}}.FMP.MOD.{{module}}.LIB.MVCS;


public abstract class TestFixtureBase : IDisposable
{
    public class TestModel : Model
    {
        public class TestStatus : Status
        {

        }

        public TestModel(string _uid) : base(_uid)
        {
        }

        protected override void setup()
        {
            Error err;
            spawnStatus<TestStatus>("test", out err);
        }
    }

    public Framework framework { get; private set; } = new Framework();
    public Logger logger { get; private set; } = new Logger();
    public Config config { get; private set; } = new Config();
    public Entry entry { get; private set; } = new Entry();
    public Model model { get; private set; } = new TestModel("test");

    public TestFixtureBase()
    {
        framework.setLogger(logger);
        framework.setConfig(config);
        framework.Initialize();

        var options = new Options();
        entry.Inject(framework, options);
        framework.setUserData("{{org}}.FMP.MOD.{{module}}.LIB.MVCS.Entry", entry);
        entry.StaticRegister("test", logger);
        framework.getStaticPipe().RegisterModel(model);
        framework.Setup();
    }

    public virtual void Dispose()
    {
        framework.Dismantle();
        framework.getStaticPipe().CancelModel(model);
        entry.StaticCancel("test", logger);
        framework.Release();
    }
}
"""


def generate(_options, _outputdir: str):
    org_name = _options["org_name"]
    module_name = _options["module_name"]
    services = _options["services"]
    database_driver = _options["database_driver"]

    contents = template.replace("{{org}}", org_name).replace("{{module}}", module_name)
    contents = contents.replace("{{version}}", _options["version"])
    filepath = os.path.join(_outputdir, "TestFixtureBase.cs")
    writer.write(filepath, contents, True)
