import os
from typing import Dict, List, Tuple
from generator.template.utility import writer

template = """
//*************************************************************************************
//   !!! Generated by the fmp-cli {{version}}.  DO NOT EDIT!
//*************************************************************************************

global using Xunit;
"""

def generate(_options, _outputdir: str):
    contents = template.replace("{{version}}", _options["version"])
    filepath = os.path.join(_outputdir, "Usings.cs")
    writer.write(filepath, contents, True)
