import os
from typing import Dict, List, Tuple
from generator.template.utility import writer

template = """
//*************************************************************************************
//   !!! Generated by the fmp-cli.  DO NOT EDIT!
//*************************************************************************************

public class DAOManager<T>
{
    private static T? dao_ { get; set; }

    public static T Value
    {
        get
        {
            if (null == dao_)
            {
                var instance = Activator.CreateInstance(typeof(T), new DatabaseOptions());
                if(null != instance)
                    dao_ = (T)instance;
            }
            return dao_!;
        }
    }
}
"""

def generate(
    _orgname: str,
    _modulename: str,
    _outputdir: str,
    _databasedriver
):
    if "mongodb" == _databasedriver:
        contents = template
        filepath = os.path.join(_outputdir, "DAOManager.cs")
        writer.write(filepath, contents, True)

