import os
from typing import Dict, List, Tuple
from generator.template.utility import writer

template_mongodb = """
//*************************************************************************************
//   !!! Generated by the fmp-cli.  DO NOT EDIT!
//*************************************************************************************

using Microsoft.Extensions.Options;
using {{org}}.FMP.MOD.{{module}}.App.Service;

public class DatabaseOptions : IOptions<DatabaseSettings>
{
    public DatabaseSettings Value
    {
        get
        {
            return new DatabaseSettings
            {
                ConnectionString = "mongodb://root:mongo%40XTC@localhost:27017",
                DatabaseName = "{{org}}_FMP_{{module}}_TEST",
            };
        }
    }
}
"""

def generate(
    _orgname: str,
    _modulename: str,
    _outputdir: str,
    _databasedriver
):
    if "mongodb" == _databasedriver:
        contents = template_mongodb.replace("{{org}}", _orgname).replace("{{module}}", _modulename)
        filepath = os.path.join(_outputdir, "DatabaseOptions.cs")
        writer.write(filepath, contents, True)

