import os
from typing import Dict, List, Tuple
from generator.template.utility import writer

template_mongodb = """
//*************************************************************************************
//   !!! Generated by the fmp-cli {{version}}.  DO NOT EDIT!
//*************************************************************************************

using Microsoft.Extensions.Options;
using {{org}}.FMP.MOD.{{module}}.App.Service;

public class DatabaseOptions : IOptions<DatabaseSettings>
{
    public DatabaseSettings Value
    {
        get
        {
            return new DatabaseSettings
            {
                ConnectionString = "mongodb://root:mongo%40XTC@localhost:27017",
                DatabaseName = "{{org}}_FMP_{{module}}_TEST",
            };
        }
    }
}
"""


def generate(_options, _outputdir: str):
    org_name = _options["org_name"]
    module_name = _options["module_name"]
    database_driver = _options["database_driver"]

    if "mongodb" == database_driver:
        contents = template_mongodb.replace("{{org}}", org_name).replace(
            "{{module}}", module_name
        )
        filepath = os.path.join(_outputdir, "DatabaseOptions.cs")
        writer.write(filepath, contents, True)
