import os
from typing import Dict, List, Tuple
from generator.template.utility import writer

template = """
//*************************************************************************************
//   !!! Generated by the fmp-cli {{version}}.  DO NOT EDIT!
//*************************************************************************************
public abstract class IntegrationTestBase
{
    [Fact]
    public abstract Task Test();
}
"""


def generate(_options, _outputdir: str):
    filepath = os.path.join(_outputdir, "IntegrationTestBase.cs")
    writer.write(filepath, template, True)
