import os
from typing import Dict, List, Tuple
from generator.template.utility import writer

template = """
//*************************************************************************************
//   !!! Generated by the fmp-cli.  DO NOT EDIT!
//*************************************************************************************

global using Xunit;
"""

def generate(
    _orgname: str,
    _modulename: str,
    _outputdir: str,
):
    filepath = os.path.join(_outputdir, "Usings.cs")
    writer.write(filepath, template, True)
