import os
from typing import Dict, List, Tuple
from generator.template.utility import writer

template_razor = """
<!--
*************************************************************************************
   !!! Generated by the fmp-cli {{version}}.  DO NOT EDIT!
*************************************************************************************
-->

@page "/"

<PageContainer Title="Welcome">
    
</PageContainer>
"""

template_css= """
.pre {
  margin: 12px 0;
  padding: 12px 20px;
  background: #fff;
  box-shadow: 0 1px 2px -2px rgba(0, 0, 0, 0.16),
    0 3px 6px 0 rgba(0, 0, 0, 0.12), 0 5px 12px 4px rgba(0, 0, 0, 0.09);
} 
"""


def generate(_options, _outputdir: str):
    sub_dir = os.path.join(_outputdir, "Pages")
    os.makedirs(sub_dir, exist_ok=True)

    contents = template_razor.replace("{{version}}", _options["version"])
    filepath_razor = os.path.join(sub_dir, "Welcome.razor")
    writer.write(filepath_razor, contents, True)

    filepath_css = os.path.join(sub_dir, "Welcome.razor.css")
    writer.write(filepath_css, template_css, True)
